repos:
- repo: https://github.com/kynan/nbstripout
  rev: master
  hooks:
    - id: nbstripout
      files: ".ipynb"

- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.7
