[tool.poetry]
authors = [
  "Ismael Mendoza <imendoza@umich.edu>",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]
description = "Studies of relationship between dark matter halo present-day properties and their growth."
keywords = ["cosmology", "haloes", "dark-matter", "nbody", "simulation"]
license = "MIT"
name = "nbody_relaxed"
packages = [{include = "relaxed"}]
readme = "README.md"
repository = "https://github.com/ismael-mendoza/nbody-relaxed"
version = "0.0.1-alpha.1"

[tool.poetry.dependencies]
astropy = "^4.2"
click = "^7.1.2"
findiff = "^0.8.9"
kllr = "^1.0.0"
matplotlib = "^3.3.3"
numpy = "^1.18.5"
pminh = {git = "https://github.com/ismael-mendoza/minnow", branch = "master"}
python = "~3.8"
scikit-image = "^0.18.0"
scikit-learn = "^0.24.1"
scipy = "^1.4.1"
ipywidgets = "^7.6.4"

[tool.poetry.dev-dependencies]
Cython = "^0.29.21"
black = "^20.8b1"
flake8 = "^3.8.4"
flake8-absolute-import = "^1.0"
jupyter-sphinx = "^0.3"
jupyterlab = "^3.0.12"
mock = "^3.0.5"
pre-commit = "^2.9.2"
pybind11 = "^2.2"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
reorder-python-imports = "^2.4.0"
sphinx = "^3.3"
sphinx-rtd-theme = "^0.4.3"
wheel = "^0.36.2"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/ismael-mendoza/nbody-relaxed/issues"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
line-length = 100
target-version = ['py38']
